[package]
name = "llm_json"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "llm_json"
path = "src/bin/main.rs"

[dependencies]
serde_json = "1.0"
thiserror = "1.0"
clap = { version = "4.0", features = ["derive"] }

[dev-dependencies]
tempfile = "3.0"
